### ISSUE TITLE
relay end point ? 

### ISSUE THREAD

**Issue by chandu0101** [sangria-graphql/sangria-akka-http-example#1]
Hi , 
      can you add relay end point also to this example ?

**Comment by OlegIlyenko** [comment]
I wanted to create a relay example in near future, but not in this repo. Because it's so coupled with the relay fronted, I was thinking about creating a small, but complete fronted/backend example application, probably with the play framework (since it's more suitable for the webapps). Do you think is would be viable option?

**Comment by OlegIlyenko** [comment]
BTW, meanwhile one full example is already available in the sangria-relay repo itself: https://github.com/sangria-graphql/sangria-relay/blob/master/src/test/scala/sangria/relay/starWars/StarWarsSchema.scala

**Comment by chandu0101** [comment]
>but not in this repo. Because it's so coupled with the relay fronted

makes sense , may be new example  project :) 

> I was thinking about creating a small, but complete fronted/backend example application

for my use i need only server end point , i want to access it from my scala.js react frontend .

**Comment by windweller** [comment]
@OlegIlyenko  Hey Oleg, any update on your Akka-HTTP Sangria-relay example? It'd be nice to have one :)
